
# Auth Server
### Login
GET http://localhost:4000/api/auth/login?user=moluram&password=moluram HTTP/1.1
Content-Type: application/json

## Response 

{
  "valid": true,
  "user": {
    "email": "moluram.a@gmail.com",
    "role": "seller"
  }
}

### Register
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "user": "moluram",
    "password": "moluram", 
    "email": "moluram.a@gmail.com", 
    "role": "seller"
}

## Response 

{
  "valid": true,
  "user": {
    "email": "asd@gmail.c",
    "role": "seller"
  }
}